### ISSUE TITLE
Safari cannot open the page because the address is invalid.

### ISSUE THREAD

**Issue by adamjbradley** [Azure-Samples/active-directory-b2c-xamarin-native#10]
"Safari cannot open the page because the address is invalid". Reply URL is set as per https://github.com/Azure-Samples/active-directory-b2c-xamarin-native

Login experience looks like this https://goo.gl/Ttp59I

**Comment by gsacavdm** [comment]
Just to confirm, is this with the default values in the sample or did it work with those and you are only having this issue when you update them to your own?

If only happening with your own, can you confirm that you specified it in all of the following:
* AppDelegate.cs
* Info.plist
* Added it to the app registration in the B2C portal.

If so, can you share the tenant name so that we can take a look from our end?

**Comment by onesimusaz** [comment]
I am having the EXACT same problem. (thanks adam for the video)

**Comment by gsacavdm** [comment]
So it worked when you ran with the default values but stopped working when you changed it to your app, your policy, etc etc. Did you confirm all three places where the redirect URI is configured? Can you provide your tenant name @onesimusaz ?

**Comment by onesimusaz** [comment]
I was never able to get the sample to work. I actually found an error in the sample that I reported to the publisher. I was able to get it to work with Android. 

Also, I am only seeing the redirect Uri defined in one place in application in AppDelegate.cs. I have confirmed that the redirect Uri is the same as the redirect Uri defined in the Application configuration in AAD b2c.

If you can provide me with an email, I will send you my tennant name.

**Comment by gsacavdm** [comment]
What error are you referring to when you say this:

>I was never able to get the sample to work. I actually found an error in the sample that I reported to the publisher.

As for the redirect Uri, for iOS, you also need to update the info.plist entry:

In the URL types, section, you also need to update the following entry:
```xml
<key>CFBundleURLSchemes</key>
<array>
 <string>msal[APPLICATIONID]</string>
</array>
```

**Comment by onesimusaz** [comment]
Is that just supposed to be the application ID or is it supposed to be the complete redirectUri?

my redirectUri is msalXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX://auth.

my CFBundleURLSchemes is 
<string>msalXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX</string>

where the Xs are my application id.

**Comment by onesimusaz** [comment]
I don't feel comfortable exposing my tenant name and application ID in a public forum. Can I send you this information some other way?

**Comment by gsacavdm** [comment]
CFBundleURLSchemes of msalXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX is correct.
I'll ping you offline to troubleshoot further.

**Comment by Mohamed-Benhazzez** [comment]
I'm facing the same issue. Please, could you help me how to fix it ?

**Comment by adamjbradley** [comment]
Gerardo,
My Tenant. Happy to provide more information if required.
//Adam

**Comment by gsacavdm** [comment]
We resolved this for @onesimusaz . I've also updated the readme with better instructions with regards to registering the web app, web API and setting the scopes.

When we've seen this, the causes have been:
* Value in `UserDetailsClient.iOS\info.plist` is incorrect, double check that it's in the form **msal[APPLICATIONID]** (no colon, slash or *'auth'*)
* Value in `UserDetailsClient.iOS\AppDelegate.cs` is incorrect, double check that it matches the full redirect URI, meaning that it **does** include colon, slash and *'auth'* like so: **msal\<Application Id>://auth**
* If you're writing the code yourself, make sure you didn't forget to add the [OpenUrl method in your UserDetailsClient.iOS/AppDelegate.cs](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/blob/master/UserDetailsClient/UserDetailsClient.iOS/AppDelegate.cs#L32)

Can you guys @Mohamed-Benhazzez and @adamjbradley  confirm all of the points above?

**Comment by Mohamed-Benhazzez** [comment]
Thanks @gsacavdm, the issue has been fixed. I updated info.plist such as below: 

<key>CFBundleURLTypes</key>
   <array>
     <dict>
       <key>CFBundleTypeRole</key>
       <string>Editor</string>
       <key>CFBundleURLName</key>
       <string>com.yourcompany.UserDetailsClient</string>
       <key>CFBundleURLSchemes</key>
       <array>
         <string>msal90c0fe63-bcf2-44d5-8fb7-b8bbc0b29dc6</string>
       </array>
     </dict>
   </array>

**Comment by gsacavdm** [comment]
Good to know @Mohamed-Benhazzez, so what the problem that you missed updating the info.plist file or did you update it but did so with the wrong value (and if so, what was the wrong value)?

**Comment by irjudson** [comment]
I am now having this problem, and have confirmed both info.plist and app.cs have the expected values.

**Comment by kanaReact** [comment]
I have the same error and solved using the following steps from the below link..
https://github.com/google/GTMAppAuth

**Comment by jennyf19** [comment]
@DominicBurford which documentation are you refering to above? I'll make sure it gets updated. Thanks.

**Comment by DominicBurford** [comment]
@jennyf19  Step 6a here https://github.com/Azure-Samples/active-directory-b2c-xamarin-native gives example code as follows:

```
<key>CFBundleURLSchemes</key>
<array>
 <string>msal[APPLICATIONID]</string>
</array>
```
It should look like this.

```
<array>
  <dict>
    <key>CFBundleURLName</key>
    <string>IfmDriverServices</string>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>msal[APPLICATIONID]</string>
    </array>
    <key>CFBundleTypeRole</key>
    <string>None</string>
  </dict>
</array>
```
The first version may work with some versions of iOS but failed to work with our app. The second version is more explicit and should therefore work on every version of iOS.

**Comment by jennyf19** [comment]
@DominicBurford Awesome! Thanks so much. I'll make sure to update the documentation.

**Comment by martinrichterlondon** [comment]
Yes, this worked: 

	<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>msalioxxx.xxxx.xxx.xxx</string>
			</array>
		</dict>

**Comment by amirvenus** [comment]
> Yes, this worked:
> 
> ```
> <dict>
> 		<key>CFBundleURLSchemes</key>
> 		<array>
> 			<string>msalioxxx.xxxx.xxx.xxx</string>
> 		</array>
> 	</dict>
> ```

My client id is 

9338bf57-7f33-4a66-bb30-51d84badd3ae

So does it need to be

```
      <dict>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>msalio9338bf57-7f33-4a66-bb30-51d84badd3ae</string>
		</array>
	</dict>
```

or 

```
      <dict>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>msal9338bf57-7f33-4a66-bb30-51d84badd3ae</string>
		</array>
	</dict>
```
